# Generated by Django 3.1.1 on 2022-07-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220729_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
