# Generated by Django 3.1.1 on 2022-07-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0027_publ_remote'),
        ('home', '0003_auto_20220729_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='username',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.publ'),
        ),
    ]
