# Generated by Django 3.1.1 on 2022-07-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220729_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
