# Generated by Django 3.1.1 on 2022-08-11 21:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_sponsor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='Investor',
        ),
    ]
