# Generated by Django 3.1.1 on 2022-08-11 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20220812_0033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investor',
            new_name='Donat',
        ),
    ]
