# Generated by Django 3.1.1 on 2022-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
