# Generated by Django 3.1.1 on 2022-06-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_wall_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='message',
            field=models.TextField(max_length=400, null=True, verbose_name='Message'),
        ),
    ]
