# Generated by Django 3.1.1 on 2022-06-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0012_auto_20220615_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400, null=True, verbose_name='Message')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('edit', models.BooleanField(default=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.DeleteModel(
            name='Wall',
        ),
    ]
