# Generated by Django 3.1.1 on 2022-06-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20220618_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publ',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
