# Generated by Django 3.1.1 on 2022-06-25 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0015_auto_20220625_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='publ',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publ',
            name='message',
            field=models.TextField(max_length=400, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='publ',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='auth.user', verbose_name='Subscriber'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Username'),
        ),
    ]
