# Generated by Django 3.1.1 on 2022-07-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
