# Generated by Django 3.1.1 on 2022-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(null=True)),
                ('like', models.PositiveIntegerField(null=True)),
                ('sum', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
