# Generated by Django 3.1.1 on 2022-07-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_auto_20220721_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='like',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
