# Generated by Django 3.1.1 on 2022-07-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_userprofile_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.FloatField(null=True),
        ),
    ]
