# Generated by Django 3.1.1 on 2022-07-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_auto_20220721_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(null=True)),
                ('sum', models.PositiveBigIntegerField(null=True)),
                ('sum_like', models.PositiveIntegerField(null=True)),
                ('sum_dislike', models.PositiveIntegerField(null=True)),
                ('positive', models.BooleanField(default=True)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.publ')),
            ],
        ),
    ]
