# Generated by Django 3.1.1 on 2022-07-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0026_auto_20220721_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='publ',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
