# Generated by Django 3.1.1 on 2022-08-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0028_auto_20220802_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
