# Generated by Django 3.1.1 on 2022-08-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0029_auto_20220802_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='publ',
            name='img_censor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publ',
            name='tag_censor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publ',
            name='text_censor',
            field=models.BooleanField(default=False),
        ),
    ]
