# Generated by Django 3.1.1 on 2022-08-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0030_auto_20220802_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publ',
            old_name='img_censor',
            new_name='censor',
        ),
        migrations.RemoveField(
            model_name='publ',
            name='tag_censor',
        ),
        migrations.RemoveField(
            model_name='publ',
            name='text_censor',
        ),
    ]
