# Generated by Django 3.1.1 on 2022-08-02 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0031_auto_20220802_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='publratinguser',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
