# Generated by Django 3.1.1 on 2022-08-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0032_publratinguser_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='publ',
            name='nude',
            field=models.BooleanField(default=False),
        ),
    ]
