# Generated by Django 3.1.1 on 2022-08-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0035_auto_20220805_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='censor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nude',
            field=models.BooleanField(default=False),
        ),
    ]
