# Generated by Django 3.1.1 on 2022-08-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0036_auto_20220805_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
