# Generated by Django 3.1.1 on 2022-08-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0037_userprofile_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='now_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
