# Generated by Django 3.1.1 on 2022-08-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0039_auto_20220808_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
