# Generated by Django 3.1.1 on 2022-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0040_userprofile_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='star',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
