# Generated by Django 3.1.1 on 2022-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0043_auto_20220817_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
