# Generated by Django 3.1.1 on 2021-03-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_restorepassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restorepassword',
            old_name='code',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='restorepassword',
            old_name='email',
            new_name='username',
        ),
    ]
