# Generated by Django 3.1.1 on 2021-03-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0008_auto_20210328_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
