# Generated by Django 3.1.1 on 2021-04-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0009_auto_20210328_0124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
