# Generated by Django 3.1.1 on 2021-04-13 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorepassword',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='restorepassword',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
    ]
