# Generated by Django 3.1.1 on 2022-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0011_auto_20210413_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
            ],
        ),
    ]
